
name: AddReviewers-PR

on:
  push:
    tags-ignore:
      - '**'
    branches-ignore:
      - 'master'
  workflow_dispatch:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest     
    steps:
    - name: test printing 
      run : |
        echo $GITHUB_RUN_ID
        echo $GITHUB_RUN_NUMBER
    
    - name: skip testing
      if: github.event.pull_request.draft == false
      run: echo skipped
      

        
    
      
