
name: AddReviewers-PR

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest     
    steps:
    - name: test printing 
      run : |
        echo $GITHUB_RUN_ID
        echo $GITHUB_RUN_NUMBER
    
    - name: skip testing
      #if: ${{ github.event.pull_request.draft == false }}
      run: |
       echo in skipped
       echo ${{ github.event.pull_request.draft}}
       echo ${{ github.workflow_dispatch}}
      

        
    
      
