
name: AddReviewers-PR

on:
  pull_request:
    branches: [ master ]
    types: [ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest     
    steps:
    - name: Add Pull Request Reviewer
      uses: uses: kentaro-m/auto-assign-action@v1.1.2
      with:
        configuration-path: '.github/auto_assign.yml'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        
    
      
