
name: AddReviewers-PR

on:
  pull_request:
    branches: [ master ]
    types: [ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest     
    steps:
    - name: Add Pull Request Reviewer
      uses: AveryCameronUofR/add-reviewer-gh-action@1.0.3
      with: 
        reviewers: "bilalshahzad139"
    
      
