
name: AddReviewers-PR

on:
  pull_request:
    types: [ready_for_review,synchronize]
    tags-ignore:
      - '**'
    branches-ignore:
      - 'main'
  workflow_dispatch:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest     
    steps:
    - name: test printing 
      run : |
        echo $GITHUB_RUN_ID
        echo $GITHUB_RUN_NUMBER
        
    
      
